H = cacode.h ephemeris.h gps.h LiquidCrystal.h Print.h spi.h
C = channel.cpp coroutines.cpp ephemeris.cpp LiquidCrystal.cpp main.cpp peri.cpp search.cpp solve.cpp spi.cpp user.cpp
F = -lrt -lfftw3f
a.out:	$(H) $(C)
	g++ $(F) $(C)
